### ISSUE TITLE
Umbraco 7.6.1 - gives error on create

### ISSUE THREAD

**Issue by blevai13** [Nicholas-Westby/usergrouppermissions#14]
Hi, we have recently installed this plugin on Umbraco 7.6.1 and it seems like we have an issue. After we set the permissions for usertypes and then we try to create and save with any users(even with administrator user type) we got a strange error message, like below, but if I clear/delete all the records in the usertypepermissions table from sql, we can create and save new content without errors.

An error occured

Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index Exception Details System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index Stacktrace

An error occurred

Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index Exception Details: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index Stacktrace:

at System.Collections.ArrayList.get_Item(Int32 index)

at System.Data.SqlClient.SqlBulkCopy.AnalyzeTargetAndCreateUpdateBulkCommand(BulkCopySimpleResultSet internalResults)

at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestContinuedAsync(BulkCopySimpleResultSet internalResults, CancellationToken cts, TaskCompletionSource`1 source)

at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestAsync(CancellationToken cts, TaskCompletionSource`1 source)

at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalAsync(CancellationToken ctoken)

at System.Data.SqlClient.SqlBulkCopy.WriteRowSourceToServerAsync(Int32 columnCount, CancellationToken ctoken)

at System.Data.SqlClient.SqlBulkCopy.WriteToServer(IDataReader reader)

at Umbraco.Core.Persistence.PetaPocoExtensions.BulkInsertRecordsSqlServer[T](Database db, SqlServerSyntaxProvider sqlSyntaxProvider, PocoData pd, IEnumerable`1 collection)

at Umbraco.Core.Persistence.PetaPocoExtensions.NativeSqlPlatformBulkInsertRecords[T](Database db, ISqlSyntaxProvider syntaxProvider, PocoData pd, IEnumerable`1 collection, Int32& processed)

at Umbraco.Core.Persistence.PetaPocoExtensions.BulkInsertRecordsTry[T](Database db, IEnumerable`1 collection, Transaction tr, ISqlSyntaxProvider syntaxProvider, Boolean useNativeSqlPlatformBulkInsert, Boolean commitTrans)

at Umbraco.Core.Persistence.PetaPocoExtensions.BulkInsertRecords[T](Database db, IEnumerable`1 collection, Transaction tr, ISqlSyntaxProvider syntaxProvider, Boolean useNativeSqlPlatformBulkInsert, Boolean commitTrans)

at UserGroupPermissions.Businesslogic.UserTypePermissionsService.CopyNodeUserTypePermissions(IContent sourceNode, IContent targetNode)

at UserGroupPermissions.Events.ContentEvents.ContentService_Saved(IContentService sender, SaveEventArgs`1 e)

at Umbraco.Core.Events.TypedEventHandler`2.Invoke(TSender sender, TEventArgs e)

at Umbraco.Core.Events.EventDefinition`2.RaiseEvent()

at Umbraco.Core.Events.ScopeEventDispatcher.ScopeExitCompleted()

at Umbraco.Core.Events.ScopeEventDispatcherBase.ScopeExit(Boolean completed)

at Umbraco.Core.Scoping.Scope.<>cDisplayClass6.b3()

at Umbraco.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions)

at Umbraco.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions)

at Umbraco.Core.Scoping.Scope.RobustExit(Boolean completed, Boolean onException)

at Umbraco.Core.Scoping.Scope.Dispose()

at Umbraco.Core.Persistence.UnitOfWork.ScopeUnitOfWork.DisposeResources()

at Umbraco.Core.DisposableObject.Dispose(Boolean disposing)

at Umbraco.Core.DisposableObject.Dispose()

at Umbraco.Core.Services.ContentService.SaveAndPublishDo(IContent content, Int32 userId, Boolean raiseEvents)

at Umbraco.Core.Services.ContentService.Umbraco.Core.Services.IContentServiceOperations.SaveAndPublish(IContent content, Int32 userId, Boolean raiseEvents)

at Umbraco.Core.Services.ContentService.SaveAndPublishWithStatus(IContent content, Int32 userId, Boolean raiseEvents)

at Umbraco.Web.Editors.ContentController.PostSave(ContentItemSave contentItem)

at lambda_method(Closure , Object , Object[] )

at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>cDisplayClass10.b9(Object instance, Object[] methodParameters)

at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Web.Http.Controllers.ApiControllerActionInvoker.d__0.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Web.Http.Filters.ActionFilterAttribute.d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Web.Http.Filters.ActionFilterAttribute.d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Web.Http.Filters.ActionFilterAttribute.d__0.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Web.Http.Filters.ActionFilterAttribute.d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Web.Http.Filters.ActionFilterAttribute.d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Web.Http.Filters.ActionFilterAttribute.d__0.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Web.Http.Filters.ActionFilterAttribute.d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Web.Http.Filters.ActionFilterAttribute.d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Web.Http.Filters.ActionFilterAttribute.d__0.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Web.Http.Filters.ActionFilterAttribute.d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Web.Http.Filters.ActionFilterAttribute.d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Web.Http.Filters.ActionFilterAttribute.d__0.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Web.Http.Filters.ActionFilterAttribute.d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Web.Http.Filters.ActionFilterAttribute.d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Web.Http.Filters.ActionFilterAttribute.d__0.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Web.Http.Filters.ActionFilterAttribute.d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Web.Http.Filters.ActionFilterAttribute.d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Web.Http.Filters.ActionFilterAttribute.d__0.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Web.Http.Controllers.ActionFilterResult.d__2.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Web.Http.Dispatcher.HttpControllerDispatcher.d__1.MoveNext()

Error Message
![umbraco_usergroup_plugin](https://user-images.githubusercontent.com/19796783/27781682-aa617108-5fd7-11e7-900f-3e95e4d588a9.JPG)

**Comment by argentini** [comment]
Same here with 7.6.3

**Comment by argentini** [comment]
Seems to only affect creating content under the home page on my web app.

**Comment by Nicholas-Westby** [comment]
Unfortunately, I don't have much time to work on this, and this package will become largely irrelevant with the release of Umbraco 7.7 (beta is currently out), which focuses on improving user groups in much the same way that this package improves user groups.

If anybody wants to dig in and attempt to address this bug, I will gladly accept a pull request. Otherwise, my recommendation would be to wait for Umbraco 7.7 and use that instead.
